# Generated by Django 4.2.27 on 2026-02-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('arreglos', '1. Arreglos florales'), ('ocasiones', '2. Ocasiones especiales'), ('condolencias', '3. Condolencias y homenajes'), ('tipo', '4. Flores por tipo'), ('plantas', '5. Plantas'), ('detalles', '6. Detalles y complementos'), ('eventos', '7. Eventos')], max_length=50)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tamano', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='catalogo/productos/')),
            ],
            options={
                'verbose_name': 'Producto del Catálogo',
                'verbose_name_plural': 'Productos del Catálogo',
            },
        ),
    ]
