# Generated by Django 4.2.27 on 2026-03-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		('catalogo', '0002_producto_activo'),
		('categoria', '0002_remove_categoria_activa'),
	]

	operations = [
		migrations.AddField(
			model_name='producto',
			name='categoria_fk',
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.PROTECT,
				related_name='+',
				to='categoria.categoria',
			),
		),
	]
