# Generated by Django 4.2.27 on 2026-03-06

import re

from django.db import migrations


def _limpiar_nombre(etiqueta: str) -> str:
	# Convierte "1. Arreglos florales" -> "Arreglos florales"
	etiqueta = (etiqueta or '').strip()
	return re.sub(r'^\s*\d+\s*\.\s*', '', etiqueta).strip() or etiqueta


def forwards(apps, schema_editor):
	Producto = apps.get_model('catalogo', 'Producto')
	Categoria = apps.get_model('categoria', 'Categoria')

	# Mapear el valor legacy (key) a una etiqueta amigable
	# Importante: esto replica el set original de choices de Producto.categoria.
	choices = {
		'arreglos': '1. Arreglos florales',
		'ocasiones': '2. Ocasiones especiales',
		'condolencias': '3. Condolencias y homenajes',
		'tipo': '4. Flores por tipo',
		'plantas': '5. Plantas',
		'detalles': '6. Detalles y complementos',
		'eventos': '7. Eventos',
	}

	categoria_por_key = {}
	for key, label in choices.items():
		nombre = _limpiar_nombre(label)
		obj, _ = Categoria.objects.get_or_create(
			nombre=nombre,
			defaults={'descripcion': ''},
		)
		categoria_por_key[key] = obj

	# Asegurar migración de datos existentes
	for producto in Producto.objects.all().only('id', 'categoria'):
		key = getattr(producto, 'categoria', None)
		categoria_obj = categoria_por_key.get(key)
		if categoria_obj is None and key:
			# Si apareciera un valor no contemplado, lo registramos como categoría
			categoria_obj, _ = Categoria.objects.get_or_create(
				nombre=str(key).strip(),
				defaults={'descripcion': ''},
			)
			categoria_por_key[key] = categoria_obj

		producto.categoria_fk = categoria_obj
		producto.save(update_fields=['categoria_fk'])


def backwards(apps, schema_editor):
	Producto = apps.get_model('catalogo', 'Producto')

	# En rollback, dejamos categoria_fk en null; la eliminación/rename se maneja en otras migraciones.
	for producto in Producto.objects.all().only('id'):
		producto.categoria_fk = None
		producto.save(update_fields=['categoria_fk'])


class Migration(migrations.Migration):

	dependencies = [
		('catalogo', '0003_producto_add_categoria_fk'),
	]

	operations = [
		migrations.RunPython(forwards, backwards),
	]
