# Generated by Django 4.2.27 on 2026-03-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		('catalogo', '0004_producto_migrate_categoria_choice_to_fk'),
	]

	operations = [
		migrations.RemoveField(
			model_name='producto',
			name='categoria',
		),
		migrations.RenameField(
			model_name='producto',
			old_name='categoria_fk',
			new_name='categoria',
		),
		migrations.AlterField(
			model_name='producto',
			name='categoria',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.PROTECT,
				related_name='productos',
				to='categoria.categoria',
			),
		),
	]
