# Generated by Django 4.2.27 on 2026-03-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('tipo_flor', models.CharField(choices=[('rosa', 'Rosas'), ('tulipan', 'Tulipanes'), ('girasol', 'Girasoles'), ('orquidea', 'Orquideas'), ('lirio', 'Lirios'), ('clavel', 'Claveles'), ('margarita', 'Margaritas'), ('hortensia', 'Hortensias'), ('mixtas', 'Flores Mixtas'), ('otras', 'Otras')], default='otras', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='flores_fotos/')),
            ],
        ),
    ]
