# Generated by Django 4.2.27 on 2026-03-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripcion', max_length=500),
        ),
    ]
