# Generated by Django 4.2.27 on 2026-03-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('tipo_producto', models.CharField(choices=[('chocolates', 'Chocolates'), ('globos', 'Globos'), ('tarjetas', 'Tarjetas'), ('peluches', 'Peluches'), ('vinos', 'Vinos'), ('dulces', 'Dulces'), ('cajas_regalo', 'Cajas de regalo'), ('decoraciones', 'Decoraciones'), ('velas', 'Velas aromaticas'), ('otros', 'Otros')], default='otros', max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos_fotos/')),
            ],
        ),
    ]
