# Generated by Django 4.2.27 on 2026-03-06

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('categoria', '0001_initial'),
	]

	operations = [
		migrations.RemoveField(
			model_name='categoria',
			name='activa',
		),
	]
