# Generated by Django 4.2.27 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('categoria', '0002_remove_categoria_activa'),
	]

	operations = [
		migrations.AddField(
			model_name='categoria',
			name='imagen',
			field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
		),
	]
