# Generated by Django 4.2.27 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('categoria', '0003_categoria_add_imagen'),
	]

	operations = [
		migrations.AddField(
			model_name='categoria',
			name='activo',
			field=models.BooleanField(default=True),
		),
	]
