# Generated by Django 4.2.27 on 2026-03-07 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0004_categoria_add_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
    ]
