# Generated by Django 4.2.27 on 2026-02-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venta', models.CharField(choices=[('BP', 'Bajo Pedido'), ('EI', 'Entrega Inmediata')], max_length=20)),
            ],
        ),
    ]
