# Generated by Django 4.2.27 on 2026-03-07 12:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flor', '0001_initial'),
        ('clientes', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venta', models.CharField(choices=[('BP', 'Bajo Pedido'), ('EI', 'Entrega Inmediata')], max_length=20)),
                ('fecha', models.DateField()),
                ('mano_obra', models.DecimalField(decimal_places=2, default=0, help_text='Costo de mano de obra', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('con_domicilio', models.BooleanField(default=False)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('FLOR', 'Flor'), ('PRODUCTO', 'Producto')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio unitario en el momento de la venta', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flor.flor')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producto.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
                'ordering': ['-created_at'],
            },
        ),
    ]
