# Generated by Django 4.2.27 on 2026-03-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nombre_domiciliario',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_domiciliario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
