# Generated by Django 4.2.27 on 2026-03-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='iva_monto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='iva_pct',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='subtotal_sin_iva',
        ),
        migrations.AddField(
            model_name='venta',
            name='nombre_domiciliario',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_domiciliario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
