# Generated by Django 4.2.27 on 2026-03-07 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='subtotal_sin_iva',
            new_name='subtotal',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='iva_pct',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='iva_monto',
        ),
    ]
