# Generated by Django 4.2.27 on 2026-03-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_nombre_domiciliario_and_more'),
    ]

    operations = [
    ]
