# Generated by Django 4.2.27 on 2026-02-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_cantidad_venta_codigo_venta_venta_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
