# Generated by Django 4.2.27 on 2026-03-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_nombre_domiciliario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='nombre_domiciliario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del domiciliario'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='telefono_domiciliario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del domiciliario'),
        ),
    ]
