# Generated by Django 4.2.27 on 2026-02-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0003_venta_direccion_venta_precio_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='codigo_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='con_domicilio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio unitario del arreglo', max_digits=10),
        ),
    ]
