# Generated by Django 4.2.27 on 2026-02-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arreglo', '0001_initial'),
        ('ventas', '0004_remove_venta_codigo_venta_remove_venta_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='arreglo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arreglo.arreglo'),
        ),
    ]
