# Generated by Django 4.2.27 on 2026-03-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_venta_options_remove_venta_arreglo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='iva_pct',
        ),
        migrations.AddField(
            model_name='venta',
            name='nombre_domiciliario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del domiciliario'),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_domiciliario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del domiciliario'),
        ),
    ]
