"""
Django settings for ARTES_Y_ESTILOS project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import Config, RepositoryEnv, config as decouple_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================================
# CARGAR ARCHIVO .env CORRECTO CON python-decouple
# ============================================================================
# Por defecto usa .env.dev; en producción pasa ENV_FILE=.env
ENV_FILE = os.getenv("ENV_FILE", ".env.dev")
env_path = BASE_DIR / ENV_FILE

if env_path.exists():
    _config = Config(RepositoryEnv(str(env_path)))
else:
    # Fallback: variables del sistema operativo
    _config = decouple_config

# ============================================================================
# SEGURIDAD
# ============================================================================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _config('SECRET_KEY', default='django-insecure-xaz3onx_0s*e)32z1ts#3z3u4q+h@wlm33(0$!^(_srtuo#09z')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = _config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# ============================================================================
# APLICACIONES INSTALADAS
# ============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'usuarios',
    'core',
    'bootstrap5',
    'catalogo',
    'proveedores',
    'clientes',
    'accesibilidad',
    'compras',
    'flor',
    'ventas',
    'producto',
    'categoria',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'usuarios.Usuario'

ROOT_URLCONF = 'ARTES_Y_ESTILOS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.panel_notificaciones',
            ],
        },
    },
]

WSGI_APPLICATION = 'ARTES_Y_ESTILOS.wsgi.application'

# ============================================================================
# BASE DE DATOS
# ============================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ============================================================================
# INTERNACIONALIZACIÓN
# ============================================================================
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# ============================================================================
# ARCHIVOS ESTÁTICOS Y MEDIA
# ============================================================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# LOGIN / LOGOUT
# ============================================================================
LOGIN_MAX_INTENTOS = 5
LOGIN_TIEMPO_BLOQUEO = 600  # segundos (10 min)

LOGIN_URL = 'usuarios:login'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'core:landing'

# ============================================================================
# SESIONES
# ============================================================================
SESSION_COOKIE_AGE = 3600
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# ============================================================================
# VALIDADORES DE CONTRASEÑA
# ============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
]

# ============================================================================
# CACHÉ
# ============================================================================
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "login-security",
    }
}

# ============================================================================
# EMAIL — CONFIGURACIÓN ÚNICA Y CORRECTA
# ============================================================================
# En .env.dev → EMAIL_BACKEND=smtp   para usar Gmail real
# En .env.dev → EMAIL_BACKEND=console para imprimir en terminal
EMAIL_BACKEND_TYPE = _config('EMAIL_BACKEND', default='console')

if EMAIL_BACKEND_TYPE == 'smtp':
    # MODO SMTP: correos reales via Gmail
    EMAIL_BACKEND    = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST       = _config('EMAIL_HOST',     default='smtp.gmail.com')
    EMAIL_PORT       = _config('EMAIL_PORT',     default=587, cast=int)
    EMAIL_USE_TLS    = _config('EMAIL_USE_TLS',  default=True, cast=bool)
    EMAIL_HOST_USER  = _config('EMAIL_HOST_USER',     default='')
    EMAIL_HOST_PASSWORD = _config('EMAIL_HOST_PASSWORD', default='')
    DEFAULT_FROM_EMAIL  = _config(
        'DEFAULT_FROM_EMAIL',
        default=f'Arte & Estilos <{EMAIL_HOST_USER}>'
    )
    SERVER_EMAIL = EMAIL_HOST_USER
else:
    # MODO CONSOLA: solo imprime en terminal, no envía nada
    EMAIL_BACKEND      = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@arteyestilos.local'
    SERVER_EMAIL       = 'noreply@arteyestilos.local'

# ============================================================================
# RECAPTCHA
# ============================================================================
RECAPTCHA_PUBLIC_KEY = _config('RECAPTCHA_PUBLIC_KEY', default='6LeRW48sAAAAABfebJ0JxbWtk-BOTFt3xNwpq0xr')
RECAPTCHA_SECRET_KEY = _config('RECAPTCHA_SECRET_KEY', default='')