# Generated by Django 4.2.27 on 2026-03-02 00:00

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(
                help_text='Documento de identidad (6-15 digitos)',
                max_length=15,
                unique=True,
                validators=[django.core.validators.RegexValidator('^\\d{6,15}$', message='El documento debe tener entre 6 y 15 digitos.')],
            ),
        ),
    ]
