# Generated by Django 4.2.27 on 2026-03-02

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(
                help_text='Documento de identidad (6-10 digitos)',
                max_length=10,
                unique=True,
                validators=[django.core.validators.RegexValidator('^\\d{6,10}$', message='El documento debe tener entre 6 y 10 digitos.')],
            ),
        ),
    ]
