# Generated by Django 4.2.27 on 2026-03-03 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(help_text='Documento de identidad (6-10 dígitos)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6,10}$', message='El documento debe tener entre 6 y 10 dígitos.')]),
        ),
    ]
