# Generated by Django 4.2.27 on 2026-03-02

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(
                'Documento',
                max_length=10,
                unique=True,
                validators=[django.core.validators.RegexValidator('^\\d{6,10}$', message='El documento debe tener entre 6 y 10 digitos.')],
                help_text='Documento (6-10 digitos)'
            ),
        ),
    ]
