# Generated by Django 4.2.27 on 2026-03-03 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(help_text='Documento (6-10 dígitos)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6,10}$', message='El documento debe tener entre 6 y 10 dígitos.')], verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('', 'Seleccione Documento...'), ('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PAS', 'Pasaporte')], max_length=10, verbose_name='Tipo de documento'),
        ),
    ]
