# Generated by Django 4.2.27 on 2026-03-07 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('flor', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('total_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Compra')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('forma_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta Debito/Credito')], max_length=20, verbose_name='Forma de Pago')),
                ('medio_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta Debito/Credito')], max_length=20, verbose_name='Medio de Pago')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('departamento', models.CharField(blank=True, max_length=45, verbose_name='Departamento')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('tipo_producto', models.CharField(blank=True, choices=[('FLOR', 'Flor'), ('PRODUCTO', 'Producto')], max_length=20, verbose_name='Tipo de Producto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_item', models.CharField(choices=[('FLOR', 'Flor'), ('PRODUCTO', 'Producto')], default='PRODUCTO', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
                ('flor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flor.flor')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producto.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'ordering': ['id'],
            },
        ),
    ]
