# Generated by Django 4.2.27 on 2026-02-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Compra')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripción')),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta Debito/Credito')], max_length=20, verbose_name='Forma de Pago')),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta Debito/Credito')], max_length=20, verbose_name='Medio de Pago')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('proveedor_id', models.CharField(max_length=45, verbose_name='ID Proveedor')),
                ('departamento', models.CharField(max_length=45, verbose_name='Departamento')),
                ('ciudad', models.CharField(max_length=45, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
