# Generated by Django 4.2.27 on 2026-02-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('FLOR', 'Flor'), ('PRODUCTO', 'Producto')], max_length=20, verbose_name='Tipo de Producto'),
        ),
    ]
