# Generated by Django 4.2.27 on 2026-03-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta Debito/Credito'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata')], max_length=20, verbose_name='Forma de Pago'),
        ),
    ]
