# Generated by Django 4.2.27 on 2026-02-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_tipo_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='descuento',
        ),
    ]
