# Generated by Django 4.2.27 on 2026-03-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_forma_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='departamento',
        ),
    ]
