# Generated by Django 4.2.27 on 2026-03-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_remove_descuento_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='departamento',
            field=models.CharField(blank=True, max_length=45, verbose_name='Departamento'),
        ),
    ]
