# Generated by Django 4.2.27 on 2026-03-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_detallecompra_item_mixto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
    ]
