# Generated by Django 4.2.27 on 2026-02-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arreglo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_flor', models.CharField(max_length=100, verbose_name='Flor (texto)')),
                ('tipo_producto', models.CharField(max_length=100, verbose_name='Producto (texto)')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('imagen', models.ImageField(upload_to='arreglos_fotos/', verbose_name='Imagen')),
            ],
        ),
    ]
