# Generated by Django 4.2.27 on 2026-03-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
