# Generated by Django 4.2.27 on 2026-03-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedor_correo_electronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='numero_documento',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
