# Generated by Django 4.2.27 on 2026-03-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_alter_proveedor_numero_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
